# Generated by Django 5.2.17 on 2026-08-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=253)),
                ("career_url", models.URLField(max_length=1000, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_enabled", models.BooleanField(default=True)),
                ("include_remote", models.BooleanField(default=True)),
                ("included_titles", models.JSONField(blank=True, default=list)),
                ("excluded_titles", models.JSONField(blank=True, default=list)),
                ("required_skill_groups", models.JSONField(blank=True, default=list)),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("excluded_skills", models.JSONField(blank=True, default=list)),
                ("employment_types", models.JSONField(blank=True, default=list)),
                ("departments", models.JSONField(blank=True, default=list)),
                ("industries", models.JSONField(blank=True, default=list)),
                ("seniority_levels", models.JSONField(blank=True, default=list)),
                ("minimum_salary", models.PositiveIntegerField(blank=True, null=True)),
                ("maximum_german_level", models.CharField(blank=True, max_length=4)),
                ("weights", models.JSONField(blank=True, default=dict)),
                ("minimum_score", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_selected_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareerSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("personio", "Personio"),
                            ("softgarden", "Softgarden"),
                            ("workday", "Workday"),
                            ("successfactors", "SAP SuccessFactors"),
                            ("json_ld", "JSON-LD"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("source_url", models.URLField(max_length=1000, unique=True)),
                ("tenant", models.CharField(blank=True, max_length=200)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("request_delay_seconds", models.PositiveSmallIntegerField(default=2)),
                ("max_pages", models.PositiveSmallIntegerField(default=100)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("last_job_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="jobs.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("jobs_seen", models.PositiveIntegerField(default=0)),
                ("jobs_created", models.PositiveIntegerField(default=0)),
                ("jobs_updated", models.PositiveIntegerField(default=0)),
                ("jobs_closed", models.PositiveIntegerField(default=0)),
                ("requests_made", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="jobs.careersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=300)),
                ("canonical_url", models.URLField(max_length=1500)),
                ("application_url", models.URLField(blank=True, max_length=1500)),
                ("title", models.CharField(max_length=500)),
                ("normalized_title", models.CharField(db_index=True, max_length=500)),
                ("description_html", models.TextField(blank=True)),
                ("description_text", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, db_index=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("country_code", models.CharField(default="DE", max_length=2)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "remote_type",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("employment_type", models.CharField(blank=True, max_length=100)),
                ("seniority", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=200)),
                (
                    "salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(default="EUR", max_length=3)),
                ("language_requirement", models.CharField(blank=True, max_length=100)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("missed_runs", models.PositiveSmallIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.careersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_km", models.PositiveSmallIntegerField(default=25)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_locations",
                        to="jobs.searchprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.SmallIntegerField()),
                ("explanation", models.JSONField(default=dict)),
                ("is_rejected", models.BooleanField(default=False)),
                ("first_matched_at", models.DateTimeField(auto_now_add=True)),
                ("last_evaluated_at", models.DateTimeField(auto_now=True)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="jobs.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="jobs.searchprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-first_matched_at"],
            },
        ),
        migrations.CreateModel(
            name="UserJobState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "No status"),
                            ("saved", "Saved"),
                            ("ignored", "Ignored"),
                            ("applied", "Applied"),
                            ("interviewing", "Interviewing"),
                            ("rejected", "Rejected"),
                            ("offer", "Offer"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_states",
                        to="jobs.workspaceuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="searchprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="jobs.workspaceuser",
            ),
        ),
        migrations.CreateModel(
            name="ExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("website", "Website"),
                            ("title", "Title"),
                            ("skill", "Skill"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pattern", models.CharField(max_length=500)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="jobs.workspaceuser",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_job_per_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilelocation",
            constraint=models.UniqueConstraint(
                fields=("profile", "city"), name="unique_city_per_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobmatch",
            constraint=models.UniqueConstraint(
                fields=("job", "profile"), name="unique_job_profile_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="userjobstate",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="unique_job_state_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_profile_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="exclusionrule",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "pattern"), name="unique_exclusion_per_user"
            ),
        ),
    ]
