# Generated by Django 5.2.17 on 2026-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="notes",
        ),
        migrations.AlterField(
            model_name="job",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
