# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_remove_company_notes_update_job_seen_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="crawlrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("source",),
                name="one_running_crawl_per_source",
            ),
        ),
    ]
