# Generated by Django 5.2.12 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_serialize_source_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("greenhouse", "Greenhouse"),
                    ("lever", "Lever"),
                    ("personio", "Personio"),
                    ("softgarden", "Softgarden"),
                    ("workday", "Workday"),
                    ("successfactors", "SAP SuccessFactors"),
                    ("json_ld", "JSON-LD"),
                    ("siemens_avature", "Siemens Avature"),
                    ("bosch_smartrecruiters", "Bosch SmartRecruiters"),
                    ("sap_successfactors", "SAP SuccessFactors Jobs2Web"),
                    ("telekom_json", "Deutsche Telekom JSON"),
                    ("dhl_phenom", "DHL Phenom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
