# Generated by Django 5.2.17 on 2026-08-26

import hashlib
import re
import unicodedata

import django.db.models.deletion
from django.db import migrations, models


def normalize(value: str) -> str:
    """Keep historical exclusion normalization stable inside this migration."""
    value = unicodedata.normalize("NFKC", value).casefold()
    value = value.replace("c#", "c sharp").replace("c++", "cplusplus")
    value = unicodedata.normalize("NFKD", value)
    value = "".join(character for character in value if not unicodedata.combining(character))
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return " ".join(value.split())


def preserve_existing_records(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    GermanPlace = apps.get_model("jobs", "GermanPlace")
    ProfileLocation = apps.get_model("jobs", "ProfileLocation")
    ExclusionRule = apps.get_model("jobs", "ExclusionRule")

    for location in ProfileLocation.objects.all().iterator():
        normalized_name = normalize(location.city)
        source_key = "\x1f".join([normalized_name, str(location.latitude), str(location.longitude)])
        source_id = "legacy:german-place:" + hashlib.sha256(source_key.encode()).hexdigest()
        place, _ = GermanPlace.objects.get_or_create(
            source_id=source_id,
            defaults={
                "name": location.city,
                "normalized_name": normalized_name,
                "latitude": location.latitude,
                "longitude": location.longitude,
                "source_kind": "city",
                "source_snapshot": "legacy",
            },
        )
        location.place_id = place.pk
        location.save(update_fields=["place"])

    seen: set[tuple[int, str, str]] = set()
    for rule in ExclusionRule.objects.order_by("pk").iterator():
        normalized_pattern = normalize(rule.pattern)
        key = (rule.user_id, rule.kind, normalized_pattern)
        if key in seen:
            rule.delete()
            continue
        seen.add(key)
        rule.normalized_pattern = normalized_pattern
        rule.save(update_fields=["normalized_pattern"])


class Migration(migrations.Migration):
    dependencies = [("jobs", "0004_add_initial_employer_source_kinds")]

    operations = [
        migrations.CreateModel(
            name="GermanPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=300, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, db_index=True, max_length=12)),
                ("admin_area", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("city", "City"), ("postal_code", "Postal code")], max_length=16
                    ),
                ),
                ("source_snapshot", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "admin_area", "postal_code"]},
        ),
        migrations.RemoveConstraint(model_name="exclusionrule", name="unique_exclusion_per_user"),
        migrations.RemoveConstraint(model_name="profilelocation", name="unique_city_per_profile"),
        migrations.AddField(
            model_name="exclusionrule",
            name="normalized_pattern",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profilelocation",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_locations",
                to="jobs.germanplace",
            ),
        ),
        migrations.RunPython(preserve_existing_records, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="exclusionrule",
            name="normalized_pattern",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profilelocation",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_locations",
                to="jobs.germanplace",
            ),
        ),
        migrations.AddConstraint(
            model_name="exclusionrule",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "normalized_pattern"), name="unique_exclusion_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="germanplace",
            constraint=models.UniqueConstraint(
                fields=("source_kind", "postal_code", "normalized_name", "latitude", "longitude"),
                name="unique_imported_german_place",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilelocation",
            constraint=models.UniqueConstraint(
                fields=("profile", "place"), name="unique_place_per_profile"
            ),
        ),
    ]
