# Generated by Django 5.2.17 on 2026-08-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_german_place_and_profile_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("company", "Company"), ("city", "City")], max_length=16
                    ),
                ),
                ("radius_km", models.PositiveSmallIntegerField(default=25)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_targets",
                        to="jobs.company",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_targets",
                        to="jobs.germanplace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_targets",
                        to="jobs.workspaceuser",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("company__isnull", False),
                                ("kind", "company"),
                                ("place__isnull", True),
                            ),
                            models.Q(
                                ("company__isnull", True),
                                ("kind", "city"),
                                ("place__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="monitoring_target_has_selection",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind", "company"),
                            models.Q(("kind", "city"), ("radius_km__gt", 0)),
                            _connector="OR",
                        ),
                        name="city_monitoring_target_has_radius",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "company")),
                        fields=("user", "company"),
                        name="unique_company_monitoring_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "city")),
                        fields=("user", "place"),
                        name="unique_city_monitoring_target",
                    ),
                ],
            },
        ),
    ]
