# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("jobs", "0008_account_city_sources")]

    operations = [
        migrations.AlterField(
            model_name="careersource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("greenhouse", "Greenhouse"),
                    ("lever", "Lever"),
                    ("personio", "Personio"),
                    ("softgarden", "Softgarden"),
                    ("dvinci", "d.vinci"),
                    ("onlyfy", "onlyfy/Prescreen"),
                    ("ashby", "Ashby"),
                    ("smartrecruiters", "SmartRecruiters"),
                    ("workable", "Workable"),
                    ("recruitee", "Recruitee"),
                    ("workday", "Workday"),
                    ("successfactors", "SAP SuccessFactors"),
                    ("json_ld", "JSON-LD"),
                    ("siemens_avature", "Siemens Avature"),
                    ("bosch_smartrecruiters", "Bosch SmartRecruiters"),
                    ("sap_successfactors", "SAP SuccessFactors Jobs2Web"),
                    ("telekom_json", "Deutsche Telekom JSON"),
                    ("dhl_phenom", "DHL Phenom"),
                ],
                default="custom",
                max_length=32,
            ),
        )
    ]
