# Generated by Django 5.2.17 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_add_public_ats_source_kinds"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerSignalSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_name", models.CharField(db_index=True, max_length=300)),
                ("employer_name", models.CharField(max_length=200)),
                ("total_active_jobs", models.PositiveIntegerField(default=0)),
                ("recent_jobs", models.PositiveIntegerField(default=0)),
                ("distinct_locations", models.JSONField(default=list)),
                ("signals", models.JSONField(default=list)),
                ("query_city", models.CharField(max_length=200)),
                ("query_radius_km", models.PositiveSmallIntegerField()),
                ("publication_age_days", models.PositiveSmallIntegerField()),
                ("is_complete", models.BooleanField(default=False)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-observed_at", "normalized_name"],
                "indexes": [
                    models.Index(
                        fields=["normalized_name", "-observed_at"],
                        name="jobs_employ_normaliz_4bb8af_idx",
                    ),
                ],
            },
        ),
    ]
