# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_employer_signal_snapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employersignalsnapshot",
            old_name="jobs_employ_normaliz_4bb8af_idx",
            new_name="jobs_employ_normali_efb108_idx",
        ),
        migrations.AddField(
            model_name="employersignalsnapshot",
            name="include_temporary_agencies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employersignalsnapshot",
            name="offer_type",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
