# Generated by Django 5.2.17 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_employer_snapshot_query_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerDiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_city", models.CharField(max_length=200)),
                ("query_radius_km", models.PositiveSmallIntegerField()),
                ("publication_age_days", models.PositiveSmallIntegerField()),
                ("offer_type", models.PositiveSmallIntegerField(default=1)),
                ("include_temporary_agencies", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-observed_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="employersignalsnapshot",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="jobs.employerdiscoveryrun",
            ),
        ),
    ]
